### ISSUE TITLE
orpheus.html: gerçek medya yüklenecek

### ISSUE THREAD

**Issue by fybx** [anticverse/com#139]
videolar ve görseller güncellenmeli

**Comment by emirhangungormez** [comment]
![Image](https://user-images.githubusercontent.com/89928334/233480188-3031d43e-ac89-45dc-9383-2ed1a2562bbb.svg)
![Image](https://user-images.githubusercontent.com/89928334/233480189-027e2897-301b-40f1-9bd9-9ccd9940be52.svg)
