### ISSUE TITLE
Not able to Create Pull Request

### ISSUE THREAD

**Issue by ajaynegi45** [anticverse/com#15]
I have made some important changes this project.

Menu bar is not working from about and contact page.
I have resolve this issue but not able to make PR 

https://github.com/anticverse/com/compare/main...ajaynegi45:com:master?expand=1

**Comment by fybx** [comment]
Can you please describe your changes and show the issue it resolves? You can provide code snippets and screenshots for comparison.

**Comment by ajaynegi45** [comment]
Problem:
On the About page, when you click on the Project or Contact menu, it will redirect you to an error page of Wix. The same problem occurs on the Contact page when you click on the Home, Products, or About menu, it will redirect you to an error page of Wix and the logo does not redirect to the home page from other pages.


Solution:
I have changed all the paths in the menu to work properly and have also edited the logo. When you click on the logo, it will now redirect you to the home page.

**Comment by fybx** [comment]
Oh, we are aware of this issue with Wix, and to solve it, I am gradually updating the pages. Thanks for your help, but the code you've committed won't be kept for long.
